name: PolyglotRocks
description: "It automates Xcode project localization using the Polyglot tool"

inputs:
  token:
    description: "The API token provided by Polyglot."
    required: true
  bundle_id:
    description: "The product bundle identifier of the Xcode project."
    required: true
  path:
    description: "The path to the directory to search files to be localized (relative to the root of the repository)."
    default: ""
    required: false
  api_url:
    description: "The URL of the API endpoint to use for localization."
    required: false
    default: "https://api.polyglot.rocks"

runs:
  using: "composite"
  steps:
    - name: pull image
      run: docker pull ghcr.io/clickcaramel/polyglot-rocks:0.1.9
      shell: bash
    - name: run polyglot
      run: |
        docker run --rm \
          --env "TOKEN=${{ inputs.token }}" \
          --env "PRODUCT_BUNDLE_IDENTIFIER=${{ inputs.bundle_id}}" \
          --env "API_URL=${{ inputs.api_url }}" \
          --volume "$(pwd)/${{ inputs.path }}:/home/polyglot/target" \
          ghcr.io/clickcaramel/polyglot-rocks:0.1.9
      shell: bash
