name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  analyze-tags:
    runs-on: ubuntu-latest
    outputs:
      latest-tag: ${{ steps.latest_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get latest tag
        id: latest_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.1.0

  cocoapods:
    runs-on: macos-latest
    needs: analyze-tags
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to CocoaPods
        run: |
          set -eo pipefail
          export LIB_VERSION=${{ needs.analyze-tags.outputs.latest-tag }}
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_PASSWORD }}
  
  docker:
    runs-on: ubuntu-latest
    needs: analyze-tags
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub CR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: bleshik
          password: ${{ secrets.CR_PAT }}
      - name: Deploy to GitHub CR
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/clickcaramel/polyglot-rocks:${{ needs.analyze-tags.outputs.latest-tag }}
            ghcr.io/clickcaramel/polyglot-rocks:latest
