name: Test Main

on:
  push:
    branches:
      - main
    paths:
      - 'bin/**'
      - 'tests/**'

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        run: |
          ./tests/run_tests.sh
