name: Test PR

on:
  pull_request:
    paths:
      - 'bin/**'
      - 'tests/**'

jobs:
  test:
    if: github.event.review.state == 'approved'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        run: |
          ./tests/run_tests.sh
